name: DevSecOps Full Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install flake8 semgrep pytest

    - name: Lint Python code
      run: flake8 app/ > lint-report.txt || true

    - name: Run Unit Tests
      run: |
        cd app
        python -m pytest tests/ -v --junitxml=../tests-report.xml

    - name: Run Semgrep (SAST)
      run: semgrep --config=p/ci --json --output semgrep-report.json || true

    - name: Build Docker image
      run: docker build -t devsecops-app .

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: devsecops-app
        format: json
        output: trivy-report.json

    - name: Start Docker container and monitoring stack
      run: |
        docker compose up -d
        # Wait for container health check
        timeout 30s bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:5000/healthz)" != "200" ]]; do sleep 2; done'
        # Verify metrics endpoint
        curl -f http://localhost:8000/metrics

    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.6.1 
      with:
        target: 'http://localhost:5000'
        docker_name: 'owasp/zap2docker-weekly'
        cmd_options: '-t http://localhost:5000 -r zap-report.html'
      fail_action: false

    - name: Run Nikto Scan
      run: |
        sudo apt-get update
        sudo apt-get install -y nikto
        nikto -h http://localhost:5000 -output nikto-report.html

    - name: Stop containers
      run: docker compose down

    - name: Upload Security and Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          lint-report.txt
          tests-report.xml
          semgrep-report.json
          trivy-report.json
          zap-report.html
          nikto-report.html